- !<Qubit>
  name: qubit
  int_freq: 5.000000E+07
  lo_name: lo_qubit
  mixer_offsets:
    I: -0.015038659097626809
    Q: -0.0019767482066527014
    G: 0.1754186229780317
    P: 0.0976141051389277
  operations:
    qubit_constant_pulse: !<ConstantPulse>
      name: qubit_constant_pulse
      I_ampx: 1.0
      Q_ampx: 0.0
      digital_marker: null
      length: 10000
      pad: 0
      total_I_amp: 0.2
      total_length: 10000
    qubit_gaussian_pulse: !<GaussianPulse>
      name: qubit_gaussian_pulse
      I_ampx: 1.0
      Q_ampx: 0.0
      chop: 4
      digital_marker: null
      pad: 0
      sigma: 200
      total_I_ampx: 0.2
      total_length: 800
    qubit_cos_ramp_pulse: !<RampedConstantPulse>
      name: qubit_cos_ramp_pulse
      I_ampx: 1.4
      Q_ampx: 0.0
      digital_marker: null
      length: 20
      pad: 0
      ramp: 10
      rampfn: cos
      total_I_amp: 0.27999999999999997
      total_length: 40
  ports:
    I: 1
    Q: 2
  rf_switch: null
  rf_switch_on: false
- !<Readout>
  name: rr
  int_freq: 5.000000E+07
  lo_name: lo_rr
  mixer_offsets:
    I: 0.0
    Q: 0.0
    G: 0.17265625
    P: 0.03281250000000001
    out: -0.011366410688920454
  operations:
    rr_constant_pulse: !<ConstantPulse>
      name: rr_constant_pulse
      I_ampx: 1.0
      Q_ampx: 0.0
      digital_marker: null
      length: 1000
      pad: 0
      total_I_amp: 0.2
      total_length: 1000
    rr_gaussian_pulse: !<GaussianPulse>
      name: rr_gaussian_pulse
      I_ampx: 1.0
      Q_ampx: 0.0
      chop: 6
      digital_marker: null
      pad: 0
      sigma: 100
      total_I_ampx: 0.2
      total_length: 600
    rr_readout_pulse: !<ConstantReadoutPulse>
      name: rr_readout_pulse
      I_ampx: 1.0
      Q_ampx: 0.0
      digital_marker: !<DigitalWaveform>
        name: ADC_ON
        samples:
        - - 1
          - 0
      has_optimized_weights: false
      length: 400
      pad: 400
      threshold: null
      total_I_amp: 0.2
      total_length: 800
      weights:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
  ports:
    I: 3
    Q: 4
    out: 1
  rf_switch: null
  rf_switch_on: false
  smearing: 0
  tof: 272
